on:
  push:
    branches:
    - master
name: Very New Build and deploy .NET Core app to Linux WebApp

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_GITHUB_SECRET }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    
    - name: Install dependencies
      run: dotnet restore samplewebproject
    
    - name: Build
      run: dotnet build samplewebproject --configuration Release --no-restore
    
    - name: Publish artifact
      run: dotnet publish samplewebproject --configuration Release --no-build --output samplewebproject/publish
    
    - uses: azure/appservice-settings@v1
      with:
        app-name: noooooooooooodelinux
        general-settings-json: '{"linuxFxVersion": "DOTNETCORE|3.1"}' #'General configuration settings as Key Value pairs'
    
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v1
      with:
        app-name: noooooooooooodelinux
        package: samplewebproject/publish

    - name: logout
      run: |
        az logout
